Improve accuracy of CUSTOM_SCHEMA definition
Change CUSTOM_SCHEMA to a dictionary mapping AnyString to Any value. This
makes error reporting more indicative of what the expected value is, by
reporting something like:
  FormatError: Expected a dict but got ‘meta’

instead of:
  FormatError: Expected a object but got 'meta'

Signed-off-by: Joshua Lock <jlock@vmware.com>