Download: Remove Content-Length header handling
These functions currently only accomplish logging: there are no actual
effects from this code... except for failure to download if the header
happens to be missing:
 TypeError: '<' not supported between instances of 'NoneType' and 'int'

Fixes #1068.

Signed-off-by: Jussi Kukkonen <jkukkonen@vmware.com>