ngclient: Fix symlink usage on Windows
Running ngclient on Windows (I believe NTFS only) leads to
  OSError: [WinError 1314] A required privilege is not held by the client

symlinking is apparently a high privilege operation: let's add a fallback.

Signed-off-by: Jussi Kukkonen <jkukkonen@google.com>