Modify load_signing_key() exception message.
The previous exception raised when a non-signing key is loaded may be misinterpreted:
tuf.Error: The private key is unavailable.

Changed to: This is not a private key.